### ISSUE TITLE
Can't train my own datasets

### ISSUE THREAD

**Issue by violetsaturn** [dBeker/Faster-RCNN-TensorFlow-Python3#77]
hey, thank you for your code , i have a problem when i try to train my own datasets.

Use standard file APIs to check for files with this prefix.
Loaded.
Fix VGG16 layers..
Fixed.
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    train.train()
  File "train.py", line 148, in train
    blobs = self.data_layer.forward()
  File "G:\object\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\roi_data
_layer.py", line 75, in forward
    blobs = self._get_next_minibatch()
  File "G:\object\Faster-RCNN-TensorFlow-Python3-master\lib\layer_utils\roi_data
_layer.py", line 71, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "G:\object\Faster-RCNN-TensorFlow-Python3-master\lib\utils\minibatch.py",
 line 30, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)
  File "G:\object\Faster-RCNN-TensorFlow-Python3-master\lib\utils\minibatch.py",
 line 63, in _get_image_blob
    im = cv2.imread(roidb[i]['image'])
KeyError: 'image'
 
i change another dataset but this problem still exit.
i have no idea about it, please help me !

**Comment by morpheusthewhite** [comment]
> im = cv2.imread(roidb[i]['image'])
> KeyError: 'image'

The problem is caused by the fact that your dataset structure is not the one that the program expects. In particular, as it is written in the error message, it misses the key "image" in the annotations

**Comment by violetsaturn** [comment]
it is must be i get a wrong in the file folder of VOCdevkit2007,
is there a teach about how to make the VOCdevkit2007 file folder with my own datasets?
thank you for your apply.

**Comment by morpheusthewhite** [comment]
First you should use the correct folder structure: `VOCdevkit2007/VOC2007` should contain
```bash
Annotations  ImageSets  JPEGImages  SegmentationClass  SegmentationObject
```
while each annotations should be like this (I'm posting the content of a file from the VOC dataset)
```xml
<annotation>
        <folder>VOC2007</folder>
        <filename>000001.jpg</filename>
        <source>
                <database>The VOC2007 Database</database>
                <annotation>PASCAL VOC2007</annotation>
                <image>flickr</image>
                <flickrid>341012865</flickrid>
        </source>
        <owner>
                <flickrid>Fried Camels</flickrid>
                <name>Jinky the Fruit Bat</name>
        </owner>
        <size>
                <width>353</width>
                <height>500</height>
                <depth>3</depth>
        </size>
        <segmented>0</segmented>
        <object>
                <name>dog</name>
                <pose>Left</pose>
                <truncated>1</truncated>
                <difficult>0</difficult>
                <bndbox>
                        <xmin>48</xmin>
                        <ymin>240</ymin>
                        <xmax>195</xmax>
                        <ymax>371</ymax>
                </bndbox>
        </object>
        <object>
                <name>person</name>
                <pose>Left</pose>
                <truncated>1</truncated>
                <difficult>0</difficult>
                <bndbox>
                        <xmin>8</xmin>
                        <ymin>12</ymin>
                        <xmax>352</xmax>
                        <ymax>498</ymax>
                </bndbox>
        </object>
</annotation>
```

To solve your problems you should replicate this (probably not all of the xml keys are needed)

**Comment by violetsaturn** [comment]
I retry to get another datasets ,but there is also something wrong........
the .xml file is as follow:

<annotation verified="yes">
	<folder>images</folder>
	<filename>raccoon-2.jpg</filename>
	<path>/Users/datitran/Desktop/raccoon/images/raccoon-2.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>800</width>
		<height>573</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>raccoon</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>60</xmin>
			<ymin>51</ymin>
			<xmax>462</xmax>
			<ymax>499</ymax>
		</bndbox>
	</object>
</annotation>

I think it is right , but the mistake also exist.  for solve this problem , I add a few words in the file of roi_data_layer.py 
that is as follow:

db_inds = self._get_next_minibatch_inds()
print('roidb[1]',self._roidb[0])
minibatch_db = [self._roidb[i] for i in db_inds]
print('mini',minibatch_db)
 
and i got the result :

roidb[1] {'boxes': array([[262, 210, 323, 338],
       [164, 263, 252, 371],
       [240, 193, 294, 298]], dtype=uint16), 'gt_classes': array([9, 9, 9]), 'gt_overlaps': <3x21 sparse matrix of type '<class 'numpy.float32'>'
	with 3 stored elements in Compressed Sparse Row format>, 'flipped': False, 'seg_areas': array([7998., 9701., 5830.], dtype=float32), 'image': 'G:\\object\\Faster-RCNN-TensorFlow-Python3-master\\data\\VOCdevkit2007\\VOC2007\\JPEGImages\\raccoon-1.jpg', 'width': 650, 'height': 417, 'max_classes': array([9, 9, 9], dtype=int64), 'max_overlaps': array([1., 1., 1.], dtype=float32)}


mini [{'boxes': array([[333,  95, 388, 275],
       [ 20, 130, 302, 343]], dtype=uint16), 'gt_classes': array([15,  7]), 'gt_overlaps': <2x21 sparse matrix of type '<class 'numpy.float32'>'
	with 2 stored elements in Compressed Sparse Row format>, 'flipped': False, 'seg_areas': array([10136., 60562.], dtype=float32)}]

i find that is very strange after '' minibatch_db = [self._roidb[i] for i in db_inds]'' this code ,the parameter of image ,width ,height are disappear  !!!!  i am so confused about this problem,when i use the  official data, this problem not exist ！！！！！

please save me !!! i have no idea about it , thank you

**Comment by morpheusthewhite** [comment]
Can you paste here the content of the .xml file correctly formatted (as I did in the previous comment)?

**Comment by morpheusthewhite** [comment]
Can you paste here the content of the .xml file correctly formatted (as I did in the previous comment)?

**Comment by violetsaturn** [comment]
```xml
 <annotation verified="yes">
	<folder>images</folder>
	<filename>raccoon-1.jpg</filename>
	<path>/Users/datitran/Desktop/raccoon/images/raccoon-1.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>650</width>
		<height>417</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>raccoon</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>81</xmin>
			<ymin>88</ymin>
			<xmax>522</xmax>
			<ymax>408</ymax>
		</bndbox>
	</object>
</annotation>
```

this is the .xml file i create, but i think it is right??

**Comment by morpheusthewhite** [comment]
Try to print the i-th image: the first one, that you printed, is correct; you should check the one used in the minibatch

**Comment by violetsaturn** [comment]
you are right ! after some image ,the 'image' parameter is disappear , but why ? Is this a parameter setting problem in the file of config.py? i print it is the number of  last image is 264.
264:{'boxes': array([[105,  63, 269, 296],
       [108,  63, 287, 463]], dtype=uint16), 'gt_classes': array([15, 13]), 'gt_overlaps': <2x21 sparse matrix of type '<class 'numpy.float32'>'
	with 2 stored elements in Compressed Sparse Row format>, 'flipped': False, 'seg_areas': array([38610., 72180.], dtype=float32), 'image': 'G:\\object\\Faster-RCNN-TensorFlow-Python3-master\\data\\VOCdevkit2007\\VOC2007\\JPEGImages\\DJI_0093.jpg', 'width': 4864, 'height': 3648, 'max_classes': array([15, 13], dtype=int64), 'max_overlaps': array([1., 1.], dtype=float32)},

265: {'boxes': array([[142,   4, 425, 332]], dtype=uint16), 'gt_classes': array([15]), 'gt_overlaps': <1x21 sparse matrix of type '<class 'numpy.float32'>'
	with 1 stored elements in Compressed Sparse Row format>, 'flipped': False, 'seg_areas': array([93436.], dtype=float32)}

**Comment by morpheusthewhite** [comment]
Almost certainly it is missing in the xml file

**Comment by violetsaturn** [comment]
I check my datasets but found nothing , so i repeated steps in 'readme', the problem is solved  !!!
thank you again ; ) 
have a nice day .

**Comment by morpheusthewhite** [comment]
You're welcome

**Comment by mp168** [comment]
I met the same problem,but i still can't solve it. when i see the answer, i thought that my dataset had some question, i check the dataset as yours, but still have problem,can you help me ?

**Comment by morpheusthewhite** [comment]
Follow the instructions, it all depends on your dataset as I have said.

Just check that you have the needed keys in the xml file (as above)

**Comment by violetsaturn** [comment]
I think it is the problem of building environment , I suggest you can retry these steps as author wrote . I retry and solve the problem.
or you can try other .xml files like the offical datasets to check if your .xml files have mistakes
